kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wujq-adm
  namespace: wujq
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log","pods/status","pods/exec","persistentvolumeclaims", "resourcequotas"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["statefulsets","statefulsets/status"]
  verbs: ["get", "list","create","delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create","delete"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["create","delete"]
- apiGroups: ["batch"]
  resources: ["jobs","jobs/status"]
  verbs: ["create","delete","get","list"]
