apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wujq-rolebinding
  namespace: wujq
subjects:
- kind: ServiceAccount
  name: default
  namespace: wujq
roleRef:
  kind: Role
  name: wujq-adm
  apiGroup: rbac.authorization.k8s.io
