apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wujq-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: wujq
roleRef:
  kind: ClusterRole
  name: wujq-cluster-adm
  apiGroup: rbac.authorization.k8s.io
