apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wujq-cluster-adm
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "nodes/status"]
  verbs: ["get", "watch", "list"]
