apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: dcgm-exporter
  name: dcgm-exporter
  namespace: monitoring
spec:
  ports:
  - name: metrics
    port: 9101
    targetPort: metrics
  selector:
    app: dcgm-exporter
